language: nix
nix: 2.1.3

before_install:
  - nix-channel --add https://nixos.org/channels/nixos-19.03 nixpkgs
  - nix-channel --update

script:
  - export PATH=$PATH:$HOME/.nix-profile/bin
  - nix-env -i elm
  - nix-env -f default.nix -i
  - pushd tests; elm-test; popd
  - pushd tests; elm-verify-examples; popd
  - pushd tests; elm-analyse; popd
  - elm-doc-preview --version
  - nix-build -A elm-test --arg compileHS true
